
server:
  port: 8010

spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    hikari:
      username: root
      password: wen175924
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          # topic 和 生产者的一样
          destination:
            add-bonus
          #stream-test-topic

          # 组,随便设置即可
          # 如果使用 RocketMQ 就一定要设置
          # 其他 MQ可留空
          group: binder-group

    nacos:
      discovery:
        # 地址
        server-addr: localhost:8848
        # 命名空间
        # namespace: eade4058-37c6-4a86-97ca-80413a7af66e
        # 集群名称
        # cluster-name: NJ
        # 元数据   k-v
        # metadata:
        #  instance: c


#rocketmq:
#  name-server: 127.0.0.1:9876

jwt:
  secret: aaaaxxxxxssdadaad
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
