server:
  port: 9000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          #让gateway从服务发现组件上面找到其他微服务
          enabled: true
      routes:
        - id: user_router
          uri: lb://user-center
          predicates:
            - Path=/users/**
        - id: content_router
          uri: lb://content-center
          predicates:
            - Path=/shares/**,/admin/**
    nacos:
      discovery:
        server-addr: localhost:8848

  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway


# 暴露所有 actuator 端点
management:
  endpoints:
    jmx:
      exposure:
        include: '*'
    # 健康检查展示详情
  endpoint:
    health:
      show-details: always
