
server:
  port: 8020

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    hikari:
      username: root
      password: wen175924
    driver-class-name: com.mysql.cj.jdbc.Driver
