
server:
  port: 8020

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    hikari:
      username: root
      password: wen175924
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
        metadata:
          k: v

# 局部配置ribbon的一种方式
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassNameom: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    #饥饿加载
    enabled: true
    clients: user-center

