
server:
  port: 8010

spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    hikari:
      username: root
      password: wen175924
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 地址
        server-addr: localhost:8848
        # 命名空间
        # namespace: eade4058-37c6-4a86-97ca-80413a7af66e
        # 集群名称
        # cluster-name: NJ
        # 元数据   k-v
        # metadata:
        #  instance: c
